version: "3.9"
services:
  frontend:
    image: nginx:1.17.3-alpine
    container_name: frontend
    volumes:
      - "./frontend/:/usr/share/nginx/html/"
      - type: bind
        source: ./nginx/duomondo.conf
        target: /etc/nginx/conf.d/duomondo.conf

    ports:
      - "8086:80"

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: backend
    command: "dotnet ./app/EndymionBackend.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_URLS=http://+:80
    volumes:
        - "./backend/:/app"
    ports:
      - "3001:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    volumes:
      - "./database:/var/opt/mssql/data/"
    environment:
      - SA_PASSWORD=#Endy432@
      - ACCEPT_EULA=Y
    ports:
      - "1414:1433"


      
