version: "3.9"
services:
  frontend6:
    image: nginx:1.17.3-alpine
    container_name: frontend-duomondo-fullstack-demo
    volumes:
      - "./frontend/:/usr/share/nginx/html/"
      - type: bind
        source: ./nginx/dev.conf
        target: /etc/nginx/conf.d/dev.conf
      - type: bind
        source: ./nginx/certs/localhost
        target: /etc/certs/localhost

    ports:
      - "8086:443"

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: backend-duomondo-fullstack-demo
    command: "dotnet ./app/EndymionBackend.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_URLS=http://+:80
    volumes:
        - "./backend/:/app"
    ports:
      - "3001:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database-duomondo-fullstack-demo
    volumes:
      - "./database:/var/opt/mssql/data/"
    environment:
      - SA_PASSWORD=#Endy432@
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"


      
